name: Android CI

on:
  push:
   branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Install dependencies
      run: git submodule update --init --recursive
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate signed APK
      run: ./gradlew assembleRelease --stacktrace

    - name: Sign APK with keystore
      uses: r0adkll/sign-android-release@v1.0.4
      id: sign_app
      with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
          BUILD_TOOLS_VERSION: "30.0.2"
    - name: Update apk
      uses: actions/upload-artifact@v2
      with:
          name: Upload signed app bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
